<?php
namespace fmr\system\template\compiler;

use fmr\system\exception\SystemException;
use fmr\util\io\AtomicWriter;
use fmr\util\StringStackUtil;

class TemplateCompiler extends TemplateScriptingCompiler {

    /**
     * Compiles the source of a template.
     *
     * @param string $templateName
     * @param string $templateContent
     * @param string $compiledFileName
     * @param array $metaData
     * @throws SystemException
     */
    public function compile(string $templateName, string $templateContent, string $compiledFileName, array $metaData): void {
        $writer = new AtomicWriter($compiledFileName);
        $writer->write("<?php\n/**\n * WebExpanded Framework TimeMonitoring \n * Template: " . $templateName . "\n * Compiled at: " . \gmdate('r') . "\n * \n * DO NOT EDIT THIS FILE\n */\n\$this->tplVars['tpl']['template'] = '" . \addcslashes(
                $templateName,
                "'\\"
            ) . "';\n?>\n");

        $compiledContent = $this->compileString($templateName, $templateContent, $metaData);
        $writer->write($compiledContent['template']);

        $this->saveMetaData($templateName, $metaData['filename'], $compiledContent['meta']);

        $writer->flush();
        $writer->close();
    }

    /**
     * Saves meta data for given template.
     *
     * @param string $templateName
     * @param string $fileName
     * @param string $content
     * @throws SystemException
     */
    public function saveMetaData($templateName, $fileName, $content): void {
        $writer = new AtomicWriter($fileName);
        $writer->write("<?php exit; /* meta data for template: " . $templateName . " (generated at " . \gmdate('r') . ") DO NOT EDIT THIS FILE */ ?>\n");
        $writer->write(serialize($content));
        $writer->flush();
        $writer->close();
    }

    /**
     * Returns the name of the current template.
     *
     * @return  string
     */
    public function getCurrentTemplate(): string {
        return $this->getCurrentIdentifier();
    }


}